print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/angelicaroque/Desktop/Game Prod/Da Game/DaGame/DaGame/Assets/Models/Gnome_Textured/Gnome.mb"`)
{		
	file -o "/Users/angelicaroque/Desktop/Game Prod/Da Game/DaGame/DaGame/Assets/Models/Gnome_Textured/Gnome.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/angelicaroque/Desktop/Game Prod/Da Game/DaGame/DaGame/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/angelicaroque/Desktop/Game Prod/Da Game/DaGame/DaGame/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/angelicaroque/Desktop/Game Prod/Da Game/DaGame/DaGame/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
